dictionary = {
    "Isis":"1",
    "Mika":"1",
    "Rosa":"1",
    "Maja K":"1",
    "Damaris":"1",
    "Maria P":"2",
    "Celia":"2",
    "Gur":"2",
    "Carine":"2",
    "Sabrina":"2",
    "Elisa":"3",
    "Dmitry":"3",
    "Sari":"3",
    "Martyna W":"3",
    "Jesper":"3",
    "Kavin":"3",
    "Kelt":"4",
    "Sebastian":"4",
    "Quanpu":"4",
    "Gabriella":"4",
    "Ruben":"4",
    "Sofia":"4",
    "Sahir":"5",
    "Kian":"5",
    "Gonzalo":"5",
    "Angeline":"6",
    "Matas":"6",
    "Raven":"6",
    "Caleb":"6",
    "Paulina":"6",
    "Angelica":"6",
    "Mate":"7",
    "Martyna P":"7",
    "Vincent":"7",
    "Eryk":"7",
    "Emma":"7",
    "Sanne":"8",
    "Beatris":"8",
    "Sally":"8",
    "Alyssa":"8",
    "Caio":"8",
    "Hielke":"8",
    "Felix":"9",
    "Diana":"9",
    "Atlas":"9",
    "Yash":"9",
    "Eliana":"9",
    "Charlie":"10",
    "Andrey":"10",
    "Akanksha":"10",
    "Hugo":"10",
    "Al-fatihi":"10",
    "Ioanna":"11",
    "Vanessa":"11",
    "Ella":"11",
    "Cristian":"11",
    "Karolina":"12",
    "Rachna":"12",
    "Luca":"12",
    "Alexia":"12",
    "Yuyue":"12",
    "Jelle":"12",
    "Maria B":"1",
    "Alicja":"11",
    "Misha":"11",
    "Tom":"5",
    "Teun":"5",
    "Ameer":"5",
    "Emily":"2",
    "Max":"10",
    "Maja M":"7",
    } 